version: 2.1

jobs:
  download-data:
    machine:
      image: ubuntu-2004:202010-01
    parameters:
      cancerType:
        type: string
        default: 'brca'
    steps:
      - checkout
      - run:
          name: Install dependencies to VM
          command: pip3 install cwltool
      - run:
          name: Download data
          command: cd ~/project/protData && cwltool prot-data-cwl-tool.cwl --cancerType << parameters.cancerType >>
      - run:
          name: Test that file was downloaded
          command: |
            if [ -f ~/project/protData/file.tsv ]; then
                echo "~/project/protData/file.tsv successfully created!"
            else
                echo "Test cases failed !!!"
                exit 1
            fi

workflows:
  test:
    jobs:
      - download-data:
          filters:
              branches:
                only:
                  - anna
