version: 2.1


filter: &filter
  filters:
    branches:
      only:
        - anna

workflows:
  test:
    jobs:
      - test-dl-brca:
          <<: *filter


executors:
  ubuntu:
    machine:
      image: ubuntu-2004:202010-01


commands:
  download-data:
    parameters:
      cancerType:
        type: string
        default: 'brca'
    steps:
      - checkout
      - run:
          name: Install dependencies to VM
          command: pip3 install cwltool
      - run:
          name: Download data
          command: cd ~/project/protData && cwltool prot-data-cwl-tool.cwl --cancerType << parameters.cancerType >>
      - run:
          name: Test that file was downloaded
          command: |
            if [ -f ~/project/protData/file.tsv ]; then
                echo "~/project/protData/file.tsv successfully created!"
            else
                echo "Test cases failed !!!"
                exit 1
            fi


jobs:
  test-dl-brca:
    executor: ubuntu
    steps:
      - download-data:
          cancerType: 'brca'
  test-dl-ccrcc:
    executor: ubuntu
    steps:
      - download-data:
          cancerType: 'ccrcc'