version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: sudo apt-get install python3.8 && sudo apt install python3-pip
      - run: pip3 install cwltool

workflows:
  test:
    jobs:
      - build
