version: 2.1


filter: &filter
  filters:
    branches:
      only:
        - anna


workflows:
  test-with-cwl:
    jobs:
#      - test-dl-brca:
#          <<: *filter
#      - test-dl-ccrcc:
#          <<: *filter
#      - test-dl-luad:
#          <<: *filter
#      - test-dl-colon:
#          <<: *filter
#      - test-dl-ovarian:
#          <<: *filter
      - test-dl-endometrial:
          <<: *filter
      - imputation:
          requires:
            - test-dl-endometrial

executors:
  ubuntu:
    machine:
      image: ubuntu-2004:202010-01


commands:
  download-data:
    parameters:
      cancerType:
        type: string
        default: 'brca'
    steps:
      - checkout
      - run:
          name: Install dependencies to VM
          command: pip3 install cwltool
      - run:
          name: Download data
          command: cd ~/project/protData && cwltool prot-data-cwl-tool.cwl --cancerType << parameters.cancerType >>
      - run:
          name: Test that file was downloaded
          command: |
            if [ -f ~/project/protData/file.tsv ]; then
                echo "~/project/protData/file.tsv successfully created!"
            else
                echo "Test cases failed !!!"
                exit 1
            fi
      - persist_to_workspace:
          root: protData
          paths:
            - file.tsv

jobs:
  test-dl-brca:
    executor: ubuntu
    steps:
      - download-data:
          cancerType: 'brca'
  test-dl-ccrcc:
    executor: ubuntu
    steps:
      - download-data:
          cancerType: 'ccrcc'
  test-dl-luad:
    executor: ubuntu
    steps:
      - download-data:
          cancerType: 'luad'
  test-dl-colon:
    executor: ubuntu
    steps:
      - download-data:
          cancerType: 'colon'
  test-dl-ovarian:
    executor: ubuntu
    steps:
      - download-data:
          cancerType: 'ovarian'
  test-dl-endometrial:
    executor: ubuntu
    steps:
      - download-data:
          cancerType: 'endometrial'
  imputation:
    executor: ubuntu
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: ls /tmp/workspace
      - run:
          name: Install dependencies to VM
          command: pip3 install cwltool
      - run:
          name: Run imputation
          command: cd ~/project/imputation && cwltool imputation-tool.cwl --input_f /tmp/workspace/file.tsv --use_missForest false



