version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Install dependencies to VM
          command: python --version

workflows:
  test:
    jobs:
      - build
