version: 2.1

jobs:
  sanity-check:
      machine:
        image: ubuntu-2004:202010-01
      steps:
        - checkout
        - run:
            name: File does not exist and should fail
            command: |
              if [ -f ~/project/protData/file.tsv ]; then
                  echo "~/project/protData/file.tsv successfully created!"
              else
                  echo "Test cases failed !!!"
                  exit 1
              fi
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Install dependencies to VM
          command: pip3 install cwltool
      - run:
          name: Download data
          command: cd ~/project/protData && cwltool prot-data-cwl-tool.cwl --cancerType brca
      - run:
          name: Test that file was downloaded
          command: |
            if [ -f ~/project/protData/file.tsv ]; then
                echo "~/project/protData/file.tsv successfully created!"
            else
                echo "Test cases failed !!!"
            fi

workflows:
  test:
    jobs:
      - sanity-check:
          filters:
              branches:
                only:
                  - anna
